In [17]:
import numpy as np


In [18]:
arr = np.array([1,2,3,4,5])
print(arr , type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [19]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr = np.array([1,2,3,4,5,6])
print(arr , arr.dtype)

[1 2 3 4 5 6] int64


In [22]:
arr1 = np.array([3 + 4j])
arr2 = np.array([6 + 3j])
print(arr1 + arr2 , arr.dtype)


[9.+7.j] int64


In [23]:
arr3 = np.array(["prime" , {1,2,3} , 3.1223])
print(arr3 , arr3.dtype)

['prime' {1, 2, 3} 3.1223] object


In [32]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4 , arr4.dtype)
print(np.sum(arr4))
sum_of_columns = np.sum(arr4 , axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr4 , axis = 1)
print(sum_of_rows)

print(arr4[:2 , :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] int64
45
[12 15 18]
[ 6 15 24]
[[1 2]
 [4 5]]
